### PR TITLE
Initial checkin of Ada SPARK 2005 Tokeneer source code

### PR DESCRIPTION
**Pull request by chrisr-diffblue**

### CODE REVIEW

**Review by martin-cs — CHANGES_REQUESTED** [review]
Are the `__MACOSX/` directories part of the initial archive?  If not, please remove them.  If they are ... I'm tempted to say a second commit that removes them is the thing to do.

**Comment by chrisr-diffblue** [comment]
They are part of the initial unzip of the Tokeneer.zip file, at least on OS X anyway - I can try on a linux VM too to see what happens there. If it's the same on both platforms, I'll do a follow up PR to remove that directory.

**Comment by martin-cs** [comment]
Sounds good.

**Comment by chrisr-diffblue** [comment]
Confirmed, unzip'ing the archive on Linux also produces the __MACOSX directory. I'll do a followup PR to remove that.

**Comment by chrisr-diffblue** [comment]
@martin-cs - I've added a 3rd commit to this PR that removes the `__MACOS` resource fork directory.

**Review by martin-cs — APPROVED** [review]

**Pull request merged**
